[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |\.vscode
  |\.pytest_cache
  |venv39
  |__pycache__
)/
'''

[tool.isort]
profile = "black"
py_version=39
skip_glob = ["venv39/*"]